name: dart_cat
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
